describe('Recipe creation', () => {
  it('user can log in and create a recipe', () => {
    cy.visit('/login')
    cy.get('input[name=email]').type('test@example.com')
    cy.get('input[name=password').type('password{enter}')
    cy.url().should('eq', 'http://localhost:3000/')
    cy.contains('Test recipe book').should('exist')
    cy.contains('Add Recipe').click()
    cy.get('textarea').type('Instructions')
    cy.get('select').select('Dessert')
    cy.get('input[name=recipeName]').type('Recipe Name{enter}')
    cy.url().should('eq', 'http://localhost:3000/')
    cy.contains('Instructions').should('exist')
    cy.contains('Read more...').should('exist')
  })
})